os:
  - linux
  - osx
sudo: required
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '6'
  - '7'
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc48; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo curl -L http://xrl.us/installperlosx | bash; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo perl -MCPAN -e 'my $c = "CPAN::HandleConfig"; $c->load(doit => 1, autoconfig => 1); $c->edit(prerequisites_policy => "follow"); $c->edit(build_requires_install_policy => "yes"); $c->commit'; fi'
  - sudo cpan install Bundle::CPAN
  - sudo cpan install Device::SerialPort
  - sudo cpan install IO::Socket::SSL
  - sudo cpan install Net::Telnet
  - sudo cpan install Net::WebSocket::Server
  - sudo cpan install XML::Simple
  - wget http://fhem.de/fhem-5.8.tar.gz
  - tar -xvzf fhem-5.8.tar.gz
  - cd fhem-5.8
  - sudo make install
  - perl /opt/fhem/fhem.pl /opt/fhem/fhem.cfg
  - cd ..
before_script:
  - npm install winston@2.3.0
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libdevice-serialport-perl
      - libwww-perl
      - libio-socket-ssl-perl
      - libcgi-pm-perl
      - libjson-perl
      - sqlite3
      - libdbd-sqlite3-perl
      - libtext-diff-perl
      - libtimedate-perl
      - libmail-imapclient-perl
      - libgd-graph-perl
      - libtext-csv-perl
      - libxml-simple-perl
      - liblist-moreutils-perl
      - ttf-liberation
      - libimage-librsvg-perl
      - libgd-text-perl
      - libsocket6-perl
      - libio-socket-inet6-perl
      - libmime-base64-perl
      - libimage-info-perl
      - libusb-1.0-0-dev
      - libnet-server-perl
