os:
  - linux
  - osx
sudo: required
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
before_script:
  - npm install winston@2.3.0
  - npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production
  #- sudo wget -qO - https://debian.fhem.de/archive.key | apt-key add -
  #- sudo deb https://debian.fhem.de/stable ./'
  #- sudo apt-get update
  #- sudo apt-get install fhem
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo curl -L http://xrl.us/installperlosx | bash; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cpan install Bundle::CPAN; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cpan install Device::SerialPort; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cpan install IO::Socket::SSL; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cpan install Net::Telnet; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cpan install Net::WebSocket::Server; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cpan install XML::Simple; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo wget http://fhem.de/fhem-5.7.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tar -xvzf fhem-5.7.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cd fhem-5.7; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo echo "define telnetPort telnet 7072 global" >> fhem.cfg; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo make install; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then perl fhem.pl fhem.cfg; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo echo "define telnetPort telnet 7072 global" >> /opt/fhem/fhem.cfg; fi

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb https://debian.fhem.de/stable ./'
      key_url: 'https://debian.fhem.de/archive.key'
    packages:
    - g++-4.8
    - fhem
